id: I22D3B62B
legacy_id: P005601
ocr_import_info:
  bdrc_scan_id: W29552
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T11:00:57'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T13:53:26.863271+00:00'
last_modified: 2022-09-02 21:53:50.885529
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W29552
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW29552
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཔྱོད་ལན་གཎཌིའི་སྒྲ་དབྱངས།
  author: རྗེས་དཀར་ཨོ་རྒྱན་བརྩོན་འགྲུས།
statistics:
  ocr_word_mean_confidence_index: 0.9435220208427733
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I5606:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5606
      total_pages: 139
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I5606.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9435220208427733
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
