id: I22D3B62B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T11:01:52+00:00'
last_modified: '2022-06-08T05:12:44.978024+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29552
  title: དཔྱོད་ལན་གཎཌིའི་སྒྲ་དབྱངས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    6AEE:
      image_group_id: I5606
      title: ''
      total_pages: 139
      order: 1
      base_file: 6AEE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
